---
name: VanillaEnchantments
version: 3.0.0
api:
- 3.0.0
author: TheAz928
website: Github.com/TheAz928/VanillaEnchantments
main: vanilla\Core
description: "Vanilla enchantments implemention for pmmp"

...
